web:
  restart: always
  build: .
  ports:
    - 8000:8000
  expose:
    - 8000
  volumes:
    - media_data:/usr/src/app/media/
  env_file: production.env
  links:
    - postgres:postgres
  command: sh '/usr/src/app/run_web.sh'

postgres:
  restart: always
  image: postgres:latest
  env_file: production.env
  ports:
    - "5432:5432"
  volumes:
    - pgdata:/var/lib/postgresqql/data/