# Generated by Django 3.0.5 on 2020-04-08 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrecord',
            name='telegram_number',
            field=models.CharField(default='', max_length=13, unique=True),
            preserve_default=False,
        ),
    ]
