# Generated by Django 3.0.5 on 2020-04-18 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrecord',
            name='rollno',
        ),
        migrations.AddField(
            model_name='userrecord',
            name='is_added_to_group',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userrecord',
            name='reason_for_error',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='userrecord',
            name='telegram_number',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='userrecord',
            name='time_added_to_group',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='userrecord',
            name='time_registered',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
