# Generated by Django 3.0.5 on 2020-04-20 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0002_auto_20200418_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrecord',
            name='time_registered',
        ),
        migrations.AlterField(
            model_name='userrecord',
            name='phone',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
