# Generated by Django 2.2.3 on 2020-04-09 04:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0002_userrecord_telegram_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrecord',
            name='is_added_to_group',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userrecord',
            name='reason_for_error',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='userrecord',
            name='time_added_to_group',
            field=models.DateTimeField(blank=True, default=datetime.datetime(1, 1, 1, 0, 0)),
        ),
        migrations.AlterField(
            model_name='userrecord',
            name='telegram_number',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True),
        ),
    ]
