# Generated by Django 2.2.3 on 2020-04-09 10:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0003_auto_20200409_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrecord',
            name='time_registered',
            field=models.DateTimeField(blank=True, default=datetime.datetime(1, 1, 1, 0, 0)),
        ),
    ]
