# Generated by Django 2.2.3 on 2020-04-09 10:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0004_userrecord_time_registered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrecord',
            name='time_added_to_group',
            field=models.DateTimeField(blank=True, default=datetime.datetime(1, 1, 1, 0, 0), null=True),
        ),
        migrations.AlterField(
            model_name='userrecord',
            name='time_registered',
            field=models.DateTimeField(blank=True, default=datetime.datetime(1, 1, 1, 0, 0), null=True),
        ),
    ]
