# Generated by Django 3.0.5 on 2020-04-10 05:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0005_auto_20200409_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrecord',
            name='time_added_to_group',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2001, 3, 19, 0, 0), null=True),
        ),
        migrations.AlterField(
            model_name='userrecord',
            name='time_registered',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2001, 3, 19, 0, 0), null=True),
        ),
    ]
